/**
 * Connect Api
 * Connect API documentation, Global rate limiting is applied: 100 requests per minute.
 *
 * OpenAPI spec version: 1.1.12-0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class User {
    'id': string;
    'email': string;
    'password': string;
    'roles': Array<UserRolesEnum>;
    'firstName'?: string;
    'lastName'?: string;
    'createdAt': Date;
    'updatedAt': Date;
    'emailVerified': boolean;
    'emailVerificationToken'?: string;
    'emailVerificationTokenExpiry'?: Date;
    'refreshToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<UserRolesEnum>",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "emailVerified",
            "baseName": "emailVerified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "emailVerificationToken",
            "baseName": "emailVerificationToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailVerificationTokenExpiry",
            "baseName": "emailVerificationTokenExpiry",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "refreshToken",
            "baseName": "refreshToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type UserRolesEnum = "client" | "tester" | "developer" ;

